src/auth.py
from flask import Blueprint, render_template, redirect, url_for, flash, current_app
from flask_login import login_user, current_user, login_required, logout_user
from src.forms import LoginForm, RegisForm
from src.models import Users
from werkzeug.security import check_password_hash

auth = Blueprint('auth', __name__)


@auth.get('/login')
def login():
    if current_user.is_authenticated:
        return redirect(url_for('views.index'))
    form = LoginForm()
    return render_template('login.html', form=form)


@auth.post('/login')
def login_post():
    form = LoginForm()
    if form.validate():
        email = form.usuario.data
        senha = form.senha.data
        remember = form.lembrar.data
        user = Users.query.filter_by(email=email).first()
        if user and check_password_hash(user.senha, senha):
            login_user(user, remember=remember)
            return redirect(url_for('views.index'))
        flash('Login ou senha inválidos!', 'danger')
        return redirect(url_for('.login'))


@auth.route('/registrar', methods=['GET', 'POST'])
def registrar():
    form = RegisForm()
    if form.validate_on_submit():
        user = Users(email=form.email.data, nome=form.nome.data, senha=form.senha.data)
        current_app.db.session.add(user)
        current_app.db.session.commit()
        flash(f'{form.nome.data.split()[0]} registrado!', 'success')
    return render_template('criarusuario.html', form=form)


# @auth.post('/registrar')
# def registrar_post():
#     form = RegisForm(request.form)
#     if form.validate_on_submit():
#         return f'{form.nome.data}'
#     return render_template('criarusuario.html', form=form)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))


def configure(app):
    app.register_blueprint(auth)

src/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_required
from src.forms import link_form_builder
from src.models import Cliente

views = Blueprint('views', __name__)


@views.route('/')
@login_required
def index():
    return render_template('index.html')


@views.route('/vender')
@login_required
def vender():
    servicos = 'FIP FIM FIS FIE FIV PAM PAE PIEDU'.split()
    print(list(request.form.items()))
    form = link_form_builder(servicos)
    return render_template('cadproposta.html', form=form)


# @views.route('/propostas')
# @login_required
# def propostas():
#     propostas = Venda.query.all()
#     return render_template('acproposta.html', propostas=propostas)


@views.get('/cliente/<cpf>')
def pesquisar(cpf):
    cliente = Cliente.query.filter_by(cpf=cpf).first()
    return render_template('cliente.html', cliente=cliente)


@views.post('/cliente/')
def pesquisar_post():
    dado = request.form.get('cpf').replace('.', '').replace('-', '').replace('(', '').replace(')', '')
    cliente = Cliente.query.filter((Cliente.cpf == dado)).first()
    if not cliente:
        flash('Não encontrado', 'danger')
        return redirect(url_for('.index'))
    return render_template('cliente.html', cliente=cliente)


def configure(app):
    app.register_blueprint(views)

src/templates/TESTE.html
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Inicio</title>
  <link rel="shortcut icon" type="image/png" href= {{ url_for('static', filename="/images/logos/ico.ico") }} />
  <link rel="stylesheet" href= {{ url_for('static', filename="/css//styles.min.css") }} />
  <link rel="style" href= {{ url_for('static', filename="/css/styles.min.css") }} >
  <link rel="stylesheet" href={{ url_for('static', filename="/css/dark-mode.css") }}  id="dark-mode-css">
  
  <style>
    body {
      transition: background-color 0.5s ease;
    }

    .sidebar-item.active .sidebar-link {
      background-color: transparent;
    }

    .dark-mode {
      background-color: #000000;
      color: #fff;
    }

    .container {
      margin-top: 100px;
      text-align: center;
    }

    .left-sidebar,
    .app-header,
    .page-wrapper {
      transition: background-color 0.5s ease, color 0.5s ease;
    }

    .dark-mode .left-sidebar,
    .dark-mode .app-header,
    .dark-mode .page-wrapper {
      background-color: #222;
      color: #fff;
    }

    .left-sidebar {
      transition: background-color 0.5s ease;
      background: linear-gradient(to bottom, #089bfe, #089ff4, #0c2d74, #0b0b18);
    }
    .left-sidebar.sidebar-degrade {
      background: linear-gradient(to bottom, #000, #000);
    }

    /* Adicione outros estilos específicos do modo escuro aqui */
    
        .sidebar-item a {
      color: #fff !important;
    }

    .sidebar-item a:hover {
      color: #aaa !important;
    }

    .sidebar-item .hide-menu {
  color: #fff !important;
    }

    .dark-mode .navbar-nav .nav-link {
      color: #fff;
    }
    
    .dark-mode .navbar-nav .nav-link:hover {
      color: #aaa;
    }
    
    /* Adicione esta regra para definir a cor do texto */
    .dark-mode,
    .dark-mode h1,
    .dark-mode p,
    .dark-mode a {
      color: #fff;
    }
  
    
    /* Estilize os botões */
    .sidebar-link button {
      padding: 3px 8px;
      border-radius: 10px;
      font-size: 14px;
    }
    
    #dark-mode-toggle {
      margin-bottom: 5px;
    }
    
    #sidebar-degrade-toggle {
      margin-top: 5px;
    }
    .btn:active {
      background-color: #ccc;
    }

  </style>
</head>

<body>
  <!--  Body Wrapper -->
  <div class="page-wrapper" id="main-wrapper" data-layout="vertical" data-navbarbg="skin6" data-sidebartype="full"
    data-sidebar-position="fixed" data-header-position="fixed">
    <!-- Sidebar Start -->
    <aside class="left-sidebar">
      <!-- Sidebar scroll-->
      <div>
        <div class="brand-logo d-flex align-items-center justify-content-between">
          <a href="./index.html" class="text-nowrap logo-img">
            <img src= {{ url_for('static', filename="images/logos/logohd_-_Copia_ZUADO_1-removebg.png") }}  width="180" alt="" id="logo-light" />
            <img src= {{ url_for('static', filename="images/logos/logohd_-_Copia_ZUADO_1-removebg.png") }} width="180" alt="" id="logo-dark" style="display: none;" />
          </a>
          <div class="close-btn d-xl-none d-block sidebartoggler cursor-pointer" id="sidebarCollapse">
            <i class="ti ti-x fs-8"></i>
          </div>
        </div>
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav scroll-sidebar" data-simplebar="">
          <ul id="sidebarnav">
            <li class="nav-small-cap">
              <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
              <span class="hide-menu" style="color: #fff;">Estilo</span>
            </li>
            <li class="">
              <a class="sidebar-link">
                <button id="dark-mode-toggle" class="btn btn-outline-light">Ativar Modo escuro</button>
              </a>
            </li>
            <li>
              <a class="sidebar-link">
                <button id="sidebar-degrade-toggle" class="btn btn-outline-light"> Tirar Degradê</button>
              </a>
            </li>
            <li class="nav-small-cap">
              <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
              <span class="hide-menu" style="color: #fff;">Home</span>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" href="./index.html" aria-expanded="false" style="background-color: transparent">
                <span>
                  <i class="ti ti-layout-dashboard"></i>
                </span>
                <span class="hide-menu" >Dashboard</span>
              </a>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" href="./cadproposta.html" aria-expanded="false">
                <span>
                  <i class="ti ti-file-description"></i>
                </span>
                <span class="hide-menu">Cadastro</span>
              </a>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" href="./acproposta.html" aria-expanded="false">
                <span>
                  <i class="ti ti-article"></i>                
                </span>
                <span class="hide-menu">Propostas</span>
              </a>
            </li>
            <li class="nav-small-cap">
              <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
              <span class="hide-menu" style="color: #fff;">FINANCEIRO</span>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" href="./financeiro.html" aria-expanded="false">
                <span>
                  <i class="ti ti-brand-mastercard"></i>               
                </span>
                <span class="hide-menu">Plataformas</span>
              </a>
            </li>
            <li class="nav-small-cap">
              <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
              <span class="hide-menu" style="color: #fff;">Graficos</span>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" href="./TESTE.html" aria-expanded="false">
                <span>
                  <i class="ti ti-brand-mastercard"></i>               
                </span>
                <span class="hide-menu">Grafana</span>
              </a>
            </li>
            <li class="nav-small-cap">
              <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
              <span class="hide-menu" style="color: #fff;">AUTH</span>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" href="./login.html" aria-expanded="false">
                <span>
                  <i class="ti ti-login"></i>
                </span>
                <span class="hide-menu">Login</span>
              </a>
            </li>
          </ul>
        </nav>
        <!-- End Sidebar navigation -->
      </div>
      <!-- End Sidebar scroll-->
    </aside>
    <!--  Sidebar End -->
    <!--  Main wrapper -->
    <div class="body-wrapper">
      <!--  Header End -->
      <!--  Content Starts -->
      <div class="page-wrapper" id="main-wrapper" data-layout="vertical" data-navbarbg="skin6" data-sidebartype="full" data-sidebar-position="fixed" data-header-position="fixed"></div>
      <div class="position-relative overflow-hidden min-vh-100 d-flex align-items-center justify-content-center">
        <div class="d-flex align-items-center justify-content-center w-100">
          <div class="row justify-content-center w-100">
            <div class="col-md-8 col-lg-6 col-xxl-3">
                  <h1>Hello, world!</h1>
            </div>
          </div>
        </div>
      </div>
    </div>
      
      <!--  Content Ends -->
    </div>
    <!--  End Main wrapper -->
  </div>
  <!--  End Body Wrapper -->
  <script src= {{ url_for('static', filename="js/vendor.min.js") }} ></script>
  <script src= {{ url_for('static', filename="js/app.min.js") }} ></script>
  <script src= {{ url_for('static', filename="libs/jquery/dist/jquery.min.js") }} ></script>
  <script src= {{ url_for('static', filename="libs/bootstrap/dist/js/bootstrap.bundle.min.js") }} ></script>
  <script src= {{ url_for('static', filename="js/sidebarmenu.js") }} ></script>
  <script src= {{ url_for('static', filename="js/app.min.js") }} ></script>
  <script src= {{ url_for('static', filename="libs/apexcharts/dist/apexcharts.min.js") }} ></script>
  <script src= {{ url_for('static', filename="libs/simplebar/dist/simplebar.js") }} ></script>
  <script src= {{ url_for('static', filename="js/script.js") }} ></script>

  <script>
    (function () {
      'use strict'

      var forms = document.querySelectorAll('.needs-validation')

      Array.prototype.slice.call(forms)
        .forEach(function (form) {
          form.addEventListener('submit', function (event) {
            if (!form.checkValidity()) {
              event.preventDefault()
              event.stopPropagation()
            }

            form.classList.add('was-validated')
          }, false)
        })
    })()

    const darkModeToggle = document.getElementById('dark-mode-toggle');
    const logoLight = document.getElementById('logo-light');
    const logoDark = document.getElementById('logo-dark');

    darkModeToggle.addEventListener('click', () => {
      const body = document.body;
      body.classList.toggle('dark-mode');
      if (body.classList.contains('dark-mode')) {
        darkModeToggle.textContent = 'Ativar Light Mode';
        logoLight.style.display = 'none';
        logoDark.style.display = 'block';
      } else {
        darkModeToggle.textContent = 'Ativar Dark Mode';
        logoLight.style.display = 'block';
        logoDark.style.display = 'none';
      }
    });

    const sidebarDegradeToggle = document.getElementById('sidebar-degrade-toggle');
    const leftSidebar = document.querySelector('.left-sidebar');

    sidebarDegradeToggle.addEventListener('click', () => {
      leftSidebar.classList.toggle('sidebar-degrade');

      if (leftSidebar.classList.contains('sidebar-degrade')) {
        sidebarDegradeToggle.textContent = 'Ativar Degradê';
      } else {
        sidebarDegradeToggle.textContent = 'Tirar Degradê';
      }
    });  
  </script>
</body>
</html>

src/templates/_flash_alerts.html
{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    {% for category, message in messages %}
      <div class="alert alert-{{ category }}" role="alert">
        {{ message }}
      </div>
    {% endfor %}
  {% endif %}
{% endwith %}

src/templates/_form_errors.html
{% macro render_error(field) %}
  {% if field.errors %}
    <ul class=list-group>
    {% for error in field.errors %}
      <li class="list-group-item list-group-item-danger">{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
{% endmacro %}

src/templates/criarusuario.html
{% extends 'sidebar.html' %}
{% block header %}  
  <title>Cadastro</title>
  <link rel="shortcut icon" type="image/png" href= "{{ url_for('static', filename='/images/logos/ico.ico') }}" />
  <link rel="stylesheet" href= "{{ url_for('static', filename='/css//styles.min.css') }}" />
  <link rel="style" href= "{{ url_for('static', filename='/css/styles.min.css') }}" >
{% endblock %}
  <!--  Body Wrapper -->
      <!--  Header End -->
      <!--  Content Starts -->
      {% block content %}
          <div class="row justify-content-center w-100">
            <div class="col-md-8 col-lg-6 col-xxl-3">
              <div class="card mb-0" style="display: flex;">
                <div class="card-body">
                  {% include '_flash_alerts.html' %}
                  <img type="img" src="{{ url_for('static', filename='/images/logos/base360.png') }}" style="width: 60%; margin: auto; display: block;">
                </a>
                <p class="text-center">Abençoado seja o usuário</p>
                  {% from "_form_errors.html" import render_error %}
                <form action="{{ url_for('auth.registrar') }}" method="POST" novalidate>
                  {{ form.hidden_tag() }}
                  <div class="mb-3">
                    {{ form.nome.label(class='form-label') }}
                    {{ form.nome(class='form-control', required=False) }}
                    {{ render_error(form.nome) }}
                  </div>
                  <div class="mb-3">
                    {{ form.email.label(class='form-label') }}
                    {{ form.email(class='form-control', required=False) }}
                    {{ render_error(form.email) }}
                  </div>
                  <div class="mb-4">
                    {{ form.senha.label(class='form-label') }}
                    {{ form.senha(class='form-control', required=False) }}
                    {{ render_error(form.senha) }}

                  </div>

                  <div class="mb-4">
                    {{ form.confirmar_senha.label(class='form-label') }}
                    {{ form.confirmar_senha(class='form-control', required=False) }}
                    {{ render_error(form.confirmar_senha) }}

                  </div>

                  <button type="submit" class="btn btn-primary w-100 py-8 fs-4 mb-4 rounded-2">Criar</button>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!--  End Body Wrapper -->
  <script src= "{{ url_for('static', filename='libs/bootstrap/dist/js/bootstrap.bundle.min.js') }}" ></script>
  <script src= "{{ url_for('static', filename='js/sidebarmenu.js') }}" ></script>
  <script src= "{{ url_for('static', filename='libs/apexcharts/dist/apexcharts.min.js') }}" ></script>

  <script>
    // Example starter JavaScript for disabling form submissions if there are invalid fields
    (function () {
      'use strict'

      // Fetch all the forms we want to apply custom Bootstrap validation styles to
      var forms = document.querySelectorAll('.needs-validation')

      // Loop over them and prevent submission
      Array.prototype.slice.call(forms)
        .forEach(function (form) {
          form.addEventListener('submit', function (event) {
            if (!form.checkValidity()) {
              event.preventDefault()
              event.stopPropagation()
            }

            form.classList.add('was-validated')
          }, false)
        })
    })()
  </script>
{% endblock %}

src/templates/index.html
{% extends 'sidebar.html' %}

{% block header %}  
<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Inicio</title>
  <link rel="shortcut icon" type="image/png" href= "{{ url_for('static', filename='/images/logos/ico.ico') }}" />
{% endblock %}
{% block content %}
          <div class="container-fluid">
            <div class="row">
              <div class="col-xl-12">
                <div class="centered">
                  <h1>Bem vindo, {{ current_user.nome.split()[0] }}</h1>
                </div>
              </div>
            </div>
          </div>
  <script src= "{{ url_for('static', filename='libs/bootstrap/dist/js/bootstrap.bundle.min.js') }}"></script>
  <script src= "{{ url_for('static', filename='libs/apexcharts/dist/apexcharts.min.js') }}" ></script>  
{% endblock %}

src/templates/login.html
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Login</title>
  <link rel="shortcut icon" type="image/png" href= "{{ url_for('static', filename='/images/logos/ico.ico') }}" />
  <link rel="stylesheet" href= "{{ url_for('static', filename='/css/styles.min.css') }}" />
  <link rel="style" href= "{{ url_for('static', filename='/css/styles.min.css') }} ">
  <script type="text/python" src="{{url_for('static', filename='scripts/login.py')}}">
  </script>

<script src="https://cdn.jsdelivr.net/npm/brython@3/brython.min.js">
</script>
</head>

<body onload="brython()">

  <!--  Body Wrapper -->
  
  <div class="page-wrapper" id="main-wrapper" data-layout="vertical" data-navbarbg="skin6" data-sidebartype="full"
    data-sidebar-position="fixed" data-header-position="fixed">
    <div class="position-relative overflow-hidden min-vh-100 d-flex align-items-center justify-content-center" style="background-color: black;">
      <div class="d-flex align-items-center justify-content-center w-100">
        <div class="row justify-content-center w-100">
          <div class="col-md-8 col-lg-6 col-xxl-3">
            <div class="card mb-0">
              <div class="card-body">
                  <img src= "{{ url_for('static', filename='images/logos/base360.png') }}"style="width: 40%; margin: auto; display: block;">
                <p class="text-center">Que seu dia seja abençoado</p>
                    {% include '_flash_alerts.html' %}
                <form action="{{ url_for('auth.login_post') }}" method="POST">
                        {{ form.hidden_tag() }}
                  <div class="mb-3">
                    {{ form.usuario.label(class='form-label') }}
                    {{ form.usuario(class='form-control') }}
                  </div>
                  <div class="mb-4">
                    {{ form.senha.label(class='form-label') }}
                    {{ form.senha(class='form-control') }}
                  </div>
                  <div class="d-flex align-items-center justify-content-between mb-4">
                    <div class="form-check">
                      {{ form.lembrar(class='form-check-input primary', checked=True) }}
                      {{ form.lembrar.label(class="form-check-label text-dark") }}
                    </div>
                    <br>
                  </div>

                    <input type="submit" class="btn btn-primary w-100 py-8 fs-4 mb-4 rounded-2">
                  </div>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script src= {{ url_for('static', filename="js/vendor.min.js") }} ></script>
  <script src= {{ url_for('static', filename="js/app.min.js") }} ></script>
  <script src= {{ url_for('static', filename="libs/jquery/dist/jquery.min.js") }} ></script>
  <script src= {{ url_for('static', filename="libs/bootstrap/dist/js/bootstrap.bundle.min.js") }} ></script>
  <script src= {{ url_for('static', filename="js/sidebarmenu.js") }} ></script>
  <script src= {{ url_for('static', filename="js/app.min.js") }} ></script>
  <script src= {{ url_for('static', filename="libs/apexcharts/dist/apexcharts.min.js") }} ></script>
  <script src= {{ url_for('static', filename="libs/simplebar/dist/simplebar.js") }} ></script>
</body>

</html>

src/templates/sidebar.html
<!doctype html>
<html lang="en">


<head>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.min.js" integrity="sha512-3gJwYpMe3QewGELv8k/BX9vcqhryRdzRMxVfq6ngyWXwo03GFEzjsUm8Q7RZcHPHksttq7/GFoxjCVUjkjvPdw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>  
<link rel="stylesheet" href= "{{ url_for('static', filename='/css/styles.min.css') }}" />
<link rel="stylesheet" href="{{ url_for('static', filename='/css/sidebar.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='/libs/simplebar/dist/simplebar.css') }}">
<script src="{{url_for('static', filename='libs/simplebar/dist/simplebar.js')}}"></script>
  <script src="https://cdn.jsdelivr.net/npm/brython@3/brython.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/brython@3/brython_stdlib.js">
</script>
<script src="https://unpkg.com/htmx.org@1.9.4" integrity="sha384-zUfuhFKKZCbHTY6aRR46gxiqszMk5tcHjsVFxnUo8VMus4kHGVdIYVbOYYNlKmHV" crossorigin="anonymous"></script>

{%block header%}
{% endblock %}
</head>

<body onload="brython()">

    <!--  Body Wrapper -->
    <div class="page-wrapper" id="main-wrapper" data-layout="vertical" data-navbarbg="skin6" data-sidebartype="full"
    data-sidebar-position="fixed" data-header-position="fixed">
    <!-- Sidebar Start -->
    <aside class="left-sidebar">
      <!-- Sidebar scroll-->
      <div>
        <div class="brand-logo d-flex align-items-center justify-content-between">
          <a href="./index.html" class="text-nowrap logo-img">
            <img src="{{ url_for('static', filename='images/logos/base360.png') }}"  width="180" alt="" id="logo-light" />
            <img src="{{ url_for('static', filename='images/logos/base360.png') }}" width="180" alt="" id="logo-dark" style="display: none;" />
          </a>
          <div class="close-btn d-xl-none d-block sidebartoggler cursor-pointer" id="sidebarCollapse">
            <i class="ti ti-x fs-8"></i>
          </div>
        </div>
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav scroll-sidebar" data-simplebar="">
          <ul id="sidebarnav">
            <li class="nav-small-cap">
              <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
              <span class="hide-menu" style="color: #fff;">Estilo</span>
            </li>
            <li class="">
              <a class="sidebar-link">
                <button id="dark-mode-toggle" class="btn btn-outline-light">Ativar Modo escuro</button>
              </a>
            </li>
            <li>
              <a class="sidebar-link">
                <button id="sidebar-degrade-toggle" class="btn btn-outline-light"> Tirar Degradê</button>
              </a>
            </li>
            <li class="nav-small-cap">
              <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
              <span class="hide-menu" style="color: #fff;">Home</span>
            </li>
            <li class="sidebar-item">
              <button class="sidebar-link" href="#" aria-expanded="false" style="background-color: transparent; border-color: transparent; color: white; ">
                <span class="ti ti-search"></span>
                <span class="hide-menu" >Pesquise</span>
              </button>
              <div id="searchInputContainer" style="display: none;">
                <form action="{{ url_for('views.pesquisar_post') }}" method="POST">
                  <input style="background-color: transparent; border-color: transparent; color: white; " name="cpf" type="text" id="searchInput" class="white-placeholder" placeholder="Digite sua pesquisa...">
                </form>
              </div>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" href="{{url_for('views.index')}}" aria-expanded="false" style="background-color: transparent">
                <span>
                  <i class="ti ti-layout-dashboard"></i>
                </span>
                <span class="hide-menu" >Dashboard</span>
              </a>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" href="{{url_for('views.vender')}}" aria-expanded="false">
                <span>
                  <i class="ti ti-file-description"></i>
                </span>
                <span class="hide-menu">Cadastro</span>
              </a>
            </li>
            <li class="nav-small-cap">
              <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
              <span class="hide-menu" style="color: #fff;">AUTH</span>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" href="{{url_for('auth.logout')}}" aria-expanded="false">
                <span>
                  <i class="ti ti-login"></i>
                </span>
                <span class="hide-menu">logout</span>
              </a>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" href="{{url_for('auth.registrar')}}" aria-expanded="false">
                <span>
                  <i class="ti ti-user"></i>
                </span>
                <span class="hide-menu">Registrar</span>
              </a>
            </li>

          </ul>
        </nav>
        <!-- End Sidebar navigation -->
      </div>
      <!-- End Sidebar scroll-->
    </aside>


    <div class="body-wrapper">
      <!--  Header Start -->
      <!--  Header End -->
      <!--  Content Starts -->
      <div class="container-fluid">
        <div class="row">
          <div class="col-xl-12">
            <div class="card">
              <div class="card-body">
                {% block content %}
                {% endblock %}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    </div>

    <script src="{{ url_for('static', filename='js/app.min.js') }}" ></script>


    <script type="text/javascript">
const searchIcon = document.querySelector('.ti-search');
const searchInputContainer = document.getElementById('searchInputContainer');
const searchInput = document.getElementById('searchInput');

// Adiciona um ouvinte de evento ao ícone da lupa para alternar entre a exibição da lupa e do campo de entrada
searchIcon.addEventListener('click', function() {
  searchIcon.style.display = 'none';
  searchInputContainer.style.display = 'block';
  searchInput.focus();
});

// Adiciona um ouvinte de evento ao documento inteiro para verificar cliques fora do campo de entrada
document.addEventListener('click', function(event) {
  // Verifica se o clique ocorreu fora do campo de entrada e do ícone da lupa
  if (event.target !== searchInput && event.target !== searchIcon) {
    searchIcon.style.display = 'block';
    searchInputContainer.style.display = 'none';
  }
});
    
    </script>
    </body>
</html>

src/templates/testeform.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
  {{form.origem}}
</head>
<body>

</body>
</html>